p8105_hw2_vy2196
================

### Problem 1

``` r
library(tidyverse)
```

    ## ── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
    ## ✔ dplyr     1.1.4     ✔ readr     2.1.5
    ## ✔ forcats   1.0.0     ✔ stringr   1.5.1
    ## ✔ ggplot2   3.5.2     ✔ tibble    3.3.0
    ## ✔ lubridate 1.9.4     ✔ tidyr     1.3.1
    ## ✔ purrr     1.1.0     
    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()
    ## ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

``` r
library(readxl)
library(janitor)
```

    ## 
    ## Attaching package: 'janitor'
    ## 
    ## The following objects are masked from 'package:stats':
    ## 
    ##     chisq.test, fisher.test

``` r
library(lubridate)
library(stringr)
library(dplyr)
library(knitr)
```

``` r
pols_month_df = read_csv(file = "data/pols-month.csv") |>
    # break up the variable 
    separate(mon, into = c("year", "month", "day"), sep = "-") |>
  # replace month number with month name
  mutate(
    year = as.integer(year),
    month = factor(month.name[as.integer(month)],
                   levels = month.name, ordered = TRUE),
    president = case_when(
      prez_gop == 1 ~ "gop",
      prez_dem == 1 ~ "dem")) |>
  select(-prez_gop, -prez_dem, -day)
pols_month_df
```

    ## # A tibble: 822 × 9
    ##     year month     gov_gop sen_gop rep_gop gov_dem sen_dem rep_dem president
    ##    <int> <ord>       <dbl>   <dbl>   <dbl>   <dbl>   <dbl>   <dbl> <chr>    
    ##  1  1947 January        23      51     253      23      45     198 dem      
    ##  2  1947 February       23      51     253      23      45     198 dem      
    ##  3  1947 March          23      51     253      23      45     198 dem      
    ##  4  1947 April          23      51     253      23      45     198 dem      
    ##  5  1947 May            23      51     253      23      45     198 dem      
    ##  6  1947 June           23      51     253      23      45     198 dem      
    ##  7  1947 July           23      51     253      23      45     198 dem      
    ##  8  1947 August         23      51     253      23      45     198 dem      
    ##  9  1947 September      23      51     253      23      45     198 dem      
    ## 10  1947 October        23      51     253      23      45     198 dem      
    ## # ℹ 812 more rows

``` r
snp_df = read_csv(file = "data/snp.csv") |>
  janitor::clean_names() |>
  separate(date, into = c("month", "day", "year"), 
           sep = "/", convert = TRUE) |>
  mutate(
    year = ifelse(year < 50, 2000 + year,
                     ifelse(year < 100, 1900 + year, year)),
    year = as.integer(year)) |>
  mutate(month = factor(month(month, label = TRUE, abbr = FALSE),
                   levels = month.name, ordered = TRUE)) |>
  arrange(year, month) |>
  select(year, month, everything(), -day)
```

    ## Rows: 787 Columns: 2
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (1): date
    ## dbl (1): close
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
snp_df
```

    ## # A tibble: 787 × 3
    ##     year month     close
    ##    <int> <ord>     <dbl>
    ##  1  1950 January    17.0
    ##  2  1950 February   17.2
    ##  3  1950 March      17.3
    ##  4  1950 April      18.0
    ##  5  1950 May        18.8
    ##  6  1950 June       17.7
    ##  7  1950 July       17.8
    ##  8  1950 August     18.4
    ##  9  1950 September  19.5
    ## 10  1950 October    19.5
    ## # ℹ 777 more rows

``` r
unemployment_df = read_csv(file = "data/unemployment.csv") |>
  # switch from wide to long
    pivot_longer(
      cols = Jan:Dec,
      names_to = "month",
      values_to = "unemployment") |>
  # Rename Year to year
  rename(year = Year) |>
  # Convert abbreviations to full month names
  mutate(
    year = as.integer(year),
    month = recode(month,
                   "Jan" = "January",
                   "Feb" = "February",
                   "Mar" = "March",
                   "Apr" = "April",
                   "May" = "May",
                   "Jun" = "June",
                   "Jul" = "July",
                   "Aug" = "August",
                   "Sep" = "September",
                   "Oct" = "October",
                   "Nov" = "November",
                   "Dec" = "December"),
    month = factor(month, levels = month.name, ordered = TRUE)) |>
  arrange(year, month) |>
  select(year, month, unemployment)
```

    ## Rows: 68 Columns: 13
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl (13): Year, Jan, Feb, Mar, Apr, May, Jun, Jul, Aug, Sep, Oct, Nov, Dec
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
unemployment_df
```

    ## # A tibble: 816 × 3
    ##     year month     unemployment
    ##    <int> <ord>            <dbl>
    ##  1  1948 January            3.4
    ##  2  1948 February           3.8
    ##  3  1948 March              4  
    ##  4  1948 April              3.9
    ##  5  1948 May                3.5
    ##  6  1948 June               3.6
    ##  7  1948 July               3.6
    ##  8  1948 August             3.9
    ##  9  1948 September          3.8
    ## 10  1948 October            3.7
    ## # ℹ 806 more rows

``` r
merged_data = 
  left_join(pols_month_df, snp_df, by = c("year", "month")) |> 
  left_join(x = _, y = unemployment_df, by = c("year", "month")) 
names(merged_data)
```

    ##  [1] "year"         "month"        "gov_gop"      "sen_gop"      "rep_gop"     
    ##  [6] "gov_dem"      "sen_dem"      "rep_dem"      "president"    "close"       
    ## [11] "unemployment"

``` r
glimpse(merged_data)
```

    ## Rows: 822
    ## Columns: 11
    ## $ year         <int> 1947, 1947, 1947, 1947, 1947, 1947, 1947, 1947, 1947, 194…
    ## $ month        <ord> January, February, March, April, May, June, July, August,…
    ## $ gov_gop      <dbl> 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 24, 24, 22, 22, 2…
    ## $ sen_gop      <dbl> 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 53, 53, 5…
    ## $ rep_gop      <dbl> 253, 253, 253, 253, 253, 253, 253, 253, 253, 253, 253, 25…
    ## $ gov_dem      <dbl> 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 24, 24, 2…
    ## $ sen_dem      <dbl> 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 48, 48, 4…
    ## $ rep_dem      <dbl> 198, 198, 198, 198, 198, 198, 198, 198, 198, 198, 198, 19…
    ## $ president    <chr> "dem", "dem", "dem", "dem", "dem", "dem", "dem", "dem", "…
    ## $ close        <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
    ## $ unemployment <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 3.4, 3.8,…

``` r
merged_data
```

    ## # A tibble: 822 × 11
    ##     year month   gov_gop sen_gop rep_gop gov_dem sen_dem rep_dem president close
    ##    <int> <ord>     <dbl>   <dbl>   <dbl>   <dbl>   <dbl>   <dbl> <chr>     <dbl>
    ##  1  1947 January      23      51     253      23      45     198 dem          NA
    ##  2  1947 Februa…      23      51     253      23      45     198 dem          NA
    ##  3  1947 March        23      51     253      23      45     198 dem          NA
    ##  4  1947 April        23      51     253      23      45     198 dem          NA
    ##  5  1947 May          23      51     253      23      45     198 dem          NA
    ##  6  1947 June         23      51     253      23      45     198 dem          NA
    ##  7  1947 July         23      51     253      23      45     198 dem          NA
    ##  8  1947 August       23      51     253      23      45     198 dem          NA
    ##  9  1947 Septem…      23      51     253      23      45     198 dem          NA
    ## 10  1947 October      23      51     253      23      45     198 dem          NA
    ## # ℹ 812 more rows
    ## # ℹ 1 more variable: unemployment <dbl>

``` r
# checking the range of year for each df
range(pols_month_df[["year"]])
```

    ## [1] 1947 2015

``` r
range(snp_df[["year"]])
```

    ## [1] 1950 2015

``` r
range(unemployment_df[["year"]])
```

    ## [1] 1948 2015

#### Decription of cleaned dataset

The dimension of `pols_month_df` is 882 x 9, and the year range is from
1947 - 2015. I separated the date and only kept `year` and `month`. I
also added a single column of `president` where its value is either
`dem` or `gop`.

The dimension of `snp_df` is 787 x 3, and the year range is from 1950 -
2015. I also separated the date and only kept `year` and `month`. I also
turned the year from 2 digits to 4 digits to match the rest of the data.

The dimension of `unemployment_df` is 816 x 3 and the year range is from
1948 - 2015. I converted the format from wide to long, and renamed the
variables of the month to match the rest of the data set.

## Problem 2

``` r
# Import and clean Mr. Trash Wheel
mr_trash = read_excel ("data/trash_wheel.xlsx", 
                       sheet = "Mr. Trash Wheel", range = "A2:N709") |>
  #Removes rows where the Dumpster column is blank
  filter(!is.na(Dumpster)) |>
  #Converts messy column names
  janitor::clean_names() |>
  mutate(
    #rounds sports ball counts to the nearest whole number
    sports_balls = as.integer(round(sports_balls)),
    year = as.integer(year),
    trash_wheel = "Mr. Trash Wheel")

mr_trash
```

    ## # A tibble: 707 × 15
    ##    dumpster month  year date                weight_tons volume_cubic_yards
    ##       <dbl> <chr> <int> <dttm>                    <dbl>              <dbl>
    ##  1        1 May    2014 2014-05-16 00:00:00        4.31                 18
    ##  2        2 May    2014 2014-05-16 00:00:00        2.74                 13
    ##  3        3 May    2014 2014-05-16 00:00:00        3.45                 15
    ##  4        4 May    2014 2014-05-17 00:00:00        3.1                  15
    ##  5        5 May    2014 2014-05-17 00:00:00        4.06                 18
    ##  6        6 May    2014 2014-05-20 00:00:00        2.71                 13
    ##  7        7 May    2014 2014-05-21 00:00:00        1.91                  8
    ##  8        8 May    2014 2014-05-28 00:00:00        3.7                  16
    ##  9        9 June   2014 2014-06-05 00:00:00        2.52                 14
    ## 10       10 June   2014 2014-06-11 00:00:00        3.76                 18
    ## # ℹ 697 more rows
    ## # ℹ 9 more variables: plastic_bottles <dbl>, polystyrene <dbl>,
    ## #   cigarette_butts <dbl>, glass_bottles <dbl>, plastic_bags <dbl>,
    ## #   wrappers <dbl>, sports_balls <int>, homes_powered <dbl>, trash_wheel <chr>

``` r
# Import and clean Professor Trash Wheel
prof_trash_wheel = read_excel ("data/trash_wheel.xlsx", 
                       sheet = "Professor Trash Wheel", range = "A2:M134") |>
  #Removes rows where the Dumpster column is blank
  filter(!is.na(Dumpster)) |>
  #Converts messy column names
  janitor::clean_names() |>
  mutate(trash_wheel = "Professor Trash Wheel",
         year = as.integer(year))

prof_trash_wheel
```

    ## # A tibble: 132 × 14
    ##    dumpster month     year date                weight_tons volume_cubic_yards
    ##       <dbl> <chr>    <int> <dttm>                    <dbl>              <dbl>
    ##  1        1 January   2017 2017-01-02 00:00:00        1.79                 15
    ##  2        2 January   2017 2017-01-30 00:00:00        1.58                 15
    ##  3        3 February  2017 2017-02-26 00:00:00        2.32                 18
    ##  4        4 February  2017 2017-02-26 00:00:00        3.72                 15
    ##  5        5 February  2017 2017-02-28 00:00:00        1.45                 15
    ##  6        6 March     2017 2017-03-30 00:00:00        1.71                 15
    ##  7        7 April     2017 2017-04-01 00:00:00        1.82                 15
    ##  8        8 April     2017 2017-04-20 00:00:00        2.37                 15
    ##  9        9 May       2017 2017-05-10 00:00:00        2.64                 15
    ## 10       10 May       2017 2017-05-26 00:00:00        2.78                 15
    ## # ℹ 122 more rows
    ## # ℹ 8 more variables: plastic_bottles <dbl>, polystyrene <dbl>,
    ## #   cigarette_butts <dbl>, glass_bottles <dbl>, plastic_bags <dbl>,
    ## #   wrappers <dbl>, homes_powered <dbl>, trash_wheel <chr>

``` r
# Import and clean Gwynns Falls Trash Wheel
gwynns_trash_wheel = read_excel ("data/trash_wheel.xlsx", 
                       sheet = "Gwynns Falls Trash Wheel") |>
  #Removes rows where the Dumpster column is blank
  filter(!is.na(Dumpster)) |>
  #Converts messy column names
  janitor::clean_names() |>
  mutate(trash_wheel = "Gwynns Falls Trash Wheel",
         year = as.integer(year))

gwynns_trash_wheel
```

    ## # A tibble: 349 × 13
    ##    dumpster month   year date                weight_tons volume_cubic_yards
    ##       <dbl> <chr>  <int> <dttm>                    <dbl>              <dbl>
    ##  1        1 July    2021 2021-07-03 00:00:00        0.93                 15
    ##  2        2 July    2021 2021-07-07 00:00:00        2.26                 15
    ##  3        3 July    2021 2021-07-07 00:00:00        1.62                 15
    ##  4        4 July    2021 2021-07-16 00:00:00        1.76                 15
    ##  5        5 July    2021 2021-07-30 00:00:00        1.53                 15
    ##  6        6 August  2021 2021-08-11 00:00:00        2.06                 15
    ##  7        7 August  2021 2021-08-14 00:00:00        1.9                  15
    ##  8        8 August  2021 2021-08-16 00:00:00        2.16                 15
    ##  9        9 August  2021 2021-08-16 00:00:00        2.6                  15
    ## 10       10 August  2021 2021-08-17 00:00:00        3.21                 15
    ## # ℹ 339 more rows
    ## # ℹ 7 more variables: plastic_bottles <dbl>, polystyrene <dbl>,
    ## #   cigarette_butts <dbl>, plastic_bags <dbl>, wrappers <dbl>,
    ## #   homes_powered <dbl>, trash_wheel <chr>

``` r
#combine data set

trash_wheel_data = bind_rows(
  mr_trash,
  prof_trash_wheel,
  gwynns_trash_wheel)

trash_wheel_data
```

    ## # A tibble: 1,188 × 15
    ##    dumpster month  year date                weight_tons volume_cubic_yards
    ##       <dbl> <chr> <int> <dttm>                    <dbl>              <dbl>
    ##  1        1 May    2014 2014-05-16 00:00:00        4.31                 18
    ##  2        2 May    2014 2014-05-16 00:00:00        2.74                 13
    ##  3        3 May    2014 2014-05-16 00:00:00        3.45                 15
    ##  4        4 May    2014 2014-05-17 00:00:00        3.1                  15
    ##  5        5 May    2014 2014-05-17 00:00:00        4.06                 18
    ##  6        6 May    2014 2014-05-20 00:00:00        2.71                 13
    ##  7        7 May    2014 2014-05-21 00:00:00        1.91                  8
    ##  8        8 May    2014 2014-05-28 00:00:00        3.7                  16
    ##  9        9 June   2014 2014-06-05 00:00:00        2.52                 14
    ## 10       10 June   2014 2014-06-11 00:00:00        3.76                 18
    ## # ℹ 1,178 more rows
    ## # ℹ 9 more variables: plastic_bottles <dbl>, polystyrene <dbl>,
    ## #   cigarette_butts <dbl>, glass_bottles <dbl>, plastic_bags <dbl>,
    ## #   wrappers <dbl>, sports_balls <int>, homes_powered <dbl>, trash_wheel <chr>

### Summary Paragraph

``` r
# Filter Gwynns June 2022
gwynns_june2022 = filter(trash_wheel_data,
                           trash_wheel == "Gwynns Falls Trash Wheel",
                           year == 2022,
                           month == "June")

# Total cigarette butts for Gwynns June 2022
gwynns_cigs_june22 = summarise(
  gwynns_june2022,
  total_cigs = sum(cigarette_butts, na.rm = TRUE)
)

# Total weight for Professor Trash Wheel
prof_total_weight = trash_wheel_data |>
  filter(trash_wheel == "Professor Trash Wheel") |>
  summarise(total_weight = sum(weight_tons, na.rm = TRUE))
```

The combined Trash Wheel data set contains 1188 observations. The key
variables include
`dumpster, month, year, date, weight, volume, plastic bottles, polystyrene, cigarette butts, glass bottles, plastic bags, wrappers, homes powered`.
The total weight of trash collected by Professor Trash Wheel is 282.3
tons of trash. Specifically for Gwynns Falls Trash Wheel on June 2022,
Gwynns collected 1.812^{4} cigarette butts.

## Problem 3

``` r
# cleaning zip_codes.csv

zip_codes_df = read_csv(file = "zillow_data/zip_codes.csv") |>
  janitor::clean_names() |>
  rename(date = file_date, county_name = county) |>
  #make sure all zip_code has 5 numbers
  mutate(ZipCode = str_pad(as.character(zip_code), 5, side = "left", pad = "0"),
         date = mdy(date)) |>
  #remove ZipCode
  select(-ZipCode, -county_code)
```

    ## Rows: 322 Columns: 7
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (4): County, County Code, File Date, Neighborhood
    ## dbl (3): State FIPS, County FIPS, ZipCode
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
# cleaning nyc_zipcodes.csv

nyc_zipcodes_df = read_csv(file = "zillow_data/nyc_zipcodes.csv") |>
  janitor::clean_names() |>
  mutate(RegionName = str_pad(as.character(region_name), 
                              5, side = "left", pad = "0")) |>
  rename(zip_code = region_name) |>
  #removing x in front of all the dates value
  rename_with(~ str_remove(.x, "^x")) |>
  #removing duplicates
  select(-region_type, -state, -RegionName)
```

    ## Rows: 149 Columns: 125
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr   (6): RegionType, StateName, State, City, Metro, CountyName
    ## dbl (119): RegionID, SizeRank, RegionName, 2015-01-31, 2015-02-28, 2015-03-3...
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
#select all the dates and match the format
date_cols = nyc_zipcodes_df |>
  #match the dates format
  select(matches("^20\\d{2}_\\d{2}_\\d{2}$")) |>
  names()

#pivot all the dates
nyc_updated_df = nyc_zipcodes_df |>
  pivot_longer(
    cols = all_of(date_cols),   # only the date columns
    #put them under data columns
    names_to = "date",
    #store their vlaues under rent
    values_to = "rent") |>
  mutate(date = lubridate::ymd(date))
```

``` r
#joining 2 datasets
final_df = zip_codes_df |>
  full_join(nyc_updated_df, by = c("zip_code", "date", "county_name"))
```

``` r
#finding unique zip_code and neighborhood
final_df |> 
  summarise(
    unique_zips = n_distinct(zip_code),
    unique_neighborhoods = n_distinct(neighborhood))
```

    ## # A tibble: 1 × 2
    ##   unique_zips unique_neighborhoods
    ##         <int>                <int>
    ## 1         320                   43

### Description of the Final Dataset

There is a total of 17,606 observations. There is 320 unique ZIP codes
and 43 unique neighborhoods.

``` r
#only zip_code in zip_codes_df
zip_only = zip_codes_df |> 
  anti_join(nyc_updated_df, by = "zip_code")

# how many unique ZIPs
zip_only |> summarise(unique_missing_zips = n_distinct(zip_code))
```

    ## # A tibble: 1 × 1
    ##   unique_missing_zips
    ##                 <int>
    ## 1                 171

There are 171 ZIP codes in the ZIP code dataset that do not appear in
the Zillow dataset. For example, the first few are: 10464, 10474, 10475,
10499, 10550. These ZIP codes might be excluded because some areas are
not traditional residential areas such as universities, military bases,
or hospitals. Another reason could be due to insufficient listings where
Zillow does not have enough rental listings to compute reliable
estimates.

``` r
#comparing rental prices

rent_change = final_df |>
  # Keep only January 2020 and 2021
  filter(month(date) == 1 & year(date) %in% c(2020, 2021)) |>
  mutate(year = year(date)) |>
  select(zip_code, borough = county_name, neighborhood, year, rent) |>
  pivot_wider(
    names_from = year,
    values_from = rent,
    names_prefix = "rent_"
  ) |>
  # Compute drop
  mutate(price_change = rent_2021 - rent_2020) |>
  arrange(price_change) |>   # most negative first
  slice_head(n = 10)

#table
kable(
  rent_change,
  caption = "Top 10 ZIP codes with largest rental price drop (Jan 2020 to Jan 2021)"
)
```

| zip_code | borough         | neighborhood | rent_2020 | rent_2021 | price_change |
|---------:|:----------------|:-------------|----------:|----------:|-------------:|
|    10007 | New York County | NA           |  6334.211 |  5421.614 |    -912.5966 |
|    10069 | New York County | NA           |  4623.042 |  3874.918 |    -748.1245 |
|    10009 | New York County | NA           |  3406.442 |  2692.187 |    -714.2550 |
|    10016 | New York County | NA           |  3731.135 |  3019.431 |    -711.7045 |
|    10001 | New York County | NA           |  4108.098 |  3397.648 |    -710.4499 |
|    10002 | New York County | NA           |  3645.416 |  2935.113 |    -710.3028 |
|    10004 | New York County | NA           |  3149.658 |  2443.697 |    -705.9608 |
|    10038 | New York County | NA           |  3573.201 |  2875.616 |    -697.5853 |
|    10012 | New York County | NA           |  3628.566 |  2942.344 |    -686.2218 |
|    10010 | New York County | NA           |  3697.284 |  3012.353 |    -684.9304 |

Top 10 ZIP codes with largest rental price drop (Jan 2020 to Jan 2021)
