---
title: "p8105_hw2_vy2196"
output: github_document
---

### Problem 1

```{r message=FALSE, warning=FALSE}
library(tidyverse)

pols_month_df = read_csv(file = "data/pols-month.csv") |>
    # break up the variable 
    separate(mon, into = c("year", "month", "day"), sep = "-") |>
  # replace month number with month name
  mutate(
    year = as.integer(year),
    month = factor(month.name[as.integer(month)],
                   levels = month.name, ordered = TRUE),
    president = case_when(
      prez_gop == 1 ~ "gop",
      prez_dem == 1 ~ "dem")) |>
  select(-prez_gop, -prez_dem, -day)
pols_month_df
```

```{r}
snp_df = read_csv(file = "data/snp.csv") |>
  janitor::clean_names() |>
  separate(date, into = c("month", "day", "year"), 
           sep = "/", convert = TRUE) |>
  mutate(
    year = ifelse(year < 50, 2000 + year,
                     ifelse(year < 100, 1900 + year, year)),
    year = as.integer(year)) |>
  mutate(month = factor(month(month, label = TRUE, abbr = FALSE),
                   levels = month.name, ordered = TRUE)) |>
  arrange(year, month) |>
  select(year, month, everything(), -day)

snp_df
```

```{r}
unemployment_df = read_csv(file = "data/unemployment.csv") |>
  # switch from wide to long
    pivot_longer(
      cols = Jan:Dec,
      names_to = "month",
      values_to = "unemployment") |>
  # Rename Year to year
  rename(year = Year) |>
  # Convert abbreviations to full month names
  mutate(
    year = as.integer(year),
    month = recode(month,
                   "Jan" = "January",
                   "Feb" = "February",
                   "Mar" = "March",
                   "Apr" = "April",
                   "May" = "May",
                   "Jun" = "June",
                   "Jul" = "July",
                   "Aug" = "August",
                   "Sep" = "September",
                   "Oct" = "October",
                   "Nov" = "November",
                   "Dec" = "December"),
    month = factor(month, levels = month.name, ordered = TRUE)) |>
  arrange(year, month) |>
  select(year, month, unemployment)
  
unemployment_df
```

```{r}
merged_data = 
  left_join(pols_month_df, snp_df, by = c("year", "month")) |> 
  left_join(x = _, y = unemployment_df, by = c("year", "month")) 
names(merged_data)
glimpse(merged_data)

merged_data

```








